# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build MAUI project Windows

on:
  push:
    branches: [ "main" ]

env:
  GAME_PROJECT: src/NonoSharp/NonoSharp.csproj
  TEST_PROJECT: tests/NonoSharp.Tests/NonoSharp.Tests.csproj
  MAUI_PROJECT: src/NonoSharp.Maui/NonoSharp.Maui.csproj

jobs:
  changed:
    runs-on: ubuntu-latest
    outputs:
      maui: ${{ steps.filter.outputs.maui }}
    steps:
      - uses: actions/checkout@v4
      - name: Check for changes in MAUI project
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            maui:
              - 'src/NonoSharp.Maui/**'

  build-maui-windows:
    needs:
      - changed

    if: needs.changed.outputs.maui == 'true'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    - name: Install .NET MAUI workload
      run: dotnet workload install maui
    - name: Build API project
      run: dotnet build -c Release ${{ env.GAME_PROJECT }}
    - name: Build MAUI project
      run: dotnet build -c Release -f net10.0-windows10.0.19041.0 ${{ env.MAUI_PROJECT }}
